# include: package:lint/analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_pub_dependencies: false
    cast_nullable_to_non_nullable: false

analyzer:
  strong-mode:
    implicit-casts: true
